### ISSUE TITLE
World Wrapping

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Unity#6]
Some progress has been made in the Core library, but the wrapping needs to be implemented in Unity so that the user's don't even notice the wrap. We should only need to render 9 maps and pan the camera between the central map and the edges of the other 8 maps surrounding it. No other motion is required other than moving the camera.

**Comment by Eliclax** [comment]
The current progress is the following:
• Outposts and Subs now use RftVectors as coordinates. This means that every time you manipulate their position, they will automatically be recalculated to lie within the equivalent point in the range (-width/2, width/2] x (-height/2, height/2].*
• There is a function in `subterfuge-unity` which, with knowledge of an object's dimensions and viewport area, will return a list of Vector2s where the object should be displayed in Unity World coords. This will only be useful for large objects that are comparable to the size of the viewport.
• All we have left to do is actually figure out how we want to turn that list into actual rendering of the game objects XD (and pirate, but that's another issue)

* I'm actually thinking of reworking the maths behind RftVectors a little so that it doesn't care which element of each equivalence class you use to represent that equivalence class. Will update this if I do.
